server:
  port: 8081
  servlet:
    contextPath: /api

spring:
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/java_learn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: off
  cloud:
    openfeign:
      okhttp:
        enabled: true
      httpclient:
        disable-ssl-validation: true

springdoc:
  swagger-ui:
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha

gigachat:
  scope: GIGACHAT_API_PERS
  model: GigaChat:latest